server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Proxy hacia events-service (evita CORS)
    location /api/events {
        proxy_pass http://events-service:5001/events;
        proxy_set_header Host $host;
        proxy_set_header traceparent $http_traceparent;
    }

    # Proxy hacia booking-service
    location /api/bookings {
        proxy_pass http://booking-service:5002/bookings;
        proxy_set_header Host $host;
        proxy_set_header traceparent $http_traceparent;
    }

    # Proxy para OTLP HTTP (traces del navegador → collector)
    location /otel/ {
        proxy_pass http://otel-collector:4318/;
        proxy_set_header Host $host;
        add_header 'Access-Control-Allow-Origin' '*' always;
    }
}
